Repository hmcts/rpe-pdf-service, pull requests merged in 2023-03, with the labels that each got.

#506 Suppress false positive - CVE-2022-45688
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-pdf-service-pr-506

#508 DTSPO-12454 Upgrade to spring boot 3
  Jenkinsfile_CNP
  README.md
  build.gradle
  config/owasp/suppressions.xml
  pdf-generator/build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/pdf/service/integration/DeprecatePDFGenerationEndpointTest.java
  src/main/java/uk/gov/hmcts/reform/pdf/service/config/DeprecatedApiConfiguration.java
  src/main/java/uk/gov/hmcts/reform/pdf/service/endpoint/RootController.java
  src/main/java/uk/gov/hmcts/reform/pdf/service/endpoint/v1/PDFGenerationEndpoint.java
  src/test/java/uk/gov/hmcts/reform/pdf/service/endpoint/v1/PDFGenerationEndpointArgumentsHandlingTest.java
Labels: ns:rpe, prd:rpe, rel:rpe-pdf-service-pr-508

#513 Switch to renovate only
  .github/dependabot.yml
  .github/renovate.json
Labels: ns:rpe, prd:rpe, rel:rpe-pdf-service-pr-513

#545 DTSPO-11734 - renovate - set schedule
  .github/renovate.json
Labels: ns:rpe, prd:rpe, rel:rpe-pdf-service-pr-545

#551 Renovate - use global presets
  .github/renovate.json
Labels: ns:rpe, prd:rpe, chore, rel:rpe-pdf-service-pr-551
